# Generated by Django 5.1.4 on 2025-01-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='pergunta')),
                ('pub_date', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
    ]
