# Generated by Django 5.1.4 on 2025-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'pergunta', 'verbose_name_plural': 'perguntas'},
        ),
    ]
